name = "vandbruno-ssr"
compatibility_date = "2025-05-20"
account_id = "508960d89e3e2fc3a887335d5c69e88f"
main = "./dist/_worker.js"
compatibility_flags = [ "nodejs_compat" ]

routes = [
  "https://www.vandbruno.net/profiles/*",
  "https://www.vandbruno.net/_astro/_username_*",
]

[observability.logs]
enabled = true

[build]
command = "npm run build"

[assets]
binding = "ASSETS"
directory = "./dist"

[triggers]
crons = []